import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import List from "@mui/material/List";
import ListItem from "@mui/material/ListItem";
import { Typography } from "@mui/material";
import PeopleIcon from "@mui/icons-material/People";

type Props = {
  activities: Activity[];
};
type Activity = {
  id: number;
  title: string;
};

const Home: NextPage<Props> = ({ activities }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Reactivities</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Typography display="flex" alignItems={"center"} variant="h5">
        <PeopleIcon /> Reactivities
      </Typography>
      <main className={styles.main}>
        <List>
          {activities.map(activity => (
            <ListItem key={activity.id}>{activity.title}</ListItem>
          ))}
        </List>
      </main>
    </div>
  );
};

export const getServerSideProps: GetServerSideProps = async context => {
  // export const getStaticProps: GetStaticProps = async context => {
  const res = await fetch("http://localhost:5000/api/activities");
  const activities = await res.json();

  return {
    props: {
      activities,
    },
  };
};

export default Home;
