import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

type Props = {
  activities: Activity[];
};
type Activity = {
  id: number;
  title: string;
};

const Home: NextPage<Props> = ({ activities }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Reactivities</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Reactivities</h1>
        <ul>
          {activities.map(activity => (
            <li key={activity.id}>{activity.title}</li>
          ))}
        </ul>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export const getServerSideProps: GetServerSideProps = async context => {
  const res = await fetch("http://localhost:5000/api/activities");
  const activities = await res.json();

  return {
    props: {
      activities,
    },
  };
};

export default Home;
